### ISSUE TITLE
My Tablet

### ISSUE THREAD

**Issue by RinOkumurra** [OpenTabletDriver/OpenTabletDriver#919] opened 2021-03-25 17:21 UTC
## Description
I can't Install the driver and if i want to use Osu!lazer my Tablet isnt getting detected.
So i tried to Install the OTD but i click on Install its just Instantly done but it doesnt work, i tried to open it again but it just says "Install" so idk what to do.

## System Information:

| Name    RinOkumurra     
| ---------------- | ----- |
| Operating System |Windows 10
| Software Version |
| Tablet           | Gaomon S620

**Comment by Mrcubix** [comment] 2021-03-25 17:24
![image](https://user-images.githubusercontent.com/39861216/112516195-50cb2200-8d97-11eb-808e-2fad7e822f66.png)

**Comment by X9VoiD** [comment] 2021-03-25 17:39
Choose either HID-compliant device or USB Input Device as the new driver to install

**Comment by RinOkumurra** [comment] 2021-03-25 17:45
https://imgur.com/v8Rhsz9
then
https://imgur.com/brAhSEx
then
https://imgur.com/RPVPeuF
ok but what now i doesnt understand

**Comment by X9VoiD** [comment] 2021-03-25 17:47
![image](https://user-images.githubusercontent.com/10338031/112519358-43348d00-8dd5-11eb-9fc8-fa85b8e108b4.png)

**Comment by RinOkumurra** [comment] 2021-03-25 17:49
ok and then what?

**Comment by Mrcubix** [comment] 2021-03-25 17:50
> Choose either HID-compliant device or USB Input Device as the new driver to install

**Comment by RinOkumurra** [comment] 2021-03-25 17:50
ok got it thanks <3

**Comment by X9VoiD** [comment] 2021-03-25 18:10
If the issue is already resolved you may close this issue now.

**Closed** 2021-03-25 18:14 UTC
Labels: bug
