### ISSUE TITLE
Support Request: Gaomon Tablet 1060 Pro is not detected

### ISSUE THREAD

**Issue by SilenceAkarin** [OpenTabletDriver/OpenTabletDriver#2989] opened 2023-11-01 11:17 UTC
### What do you need help with?

I just got my hands on the Gaomon 1060Pro and I tried to connect it to OpenTabletDriver but it didn't work. I have never used a tablet, i've tried to remove driver and reinstall driver, but still not work

### What have you tried?

i search issues [#2916] and [#2899] and tried to new folder and put .json in it
then i reopen OPT, the problem still exists
![image](https://github.com/OpenTabletDriver/OpenTabletDriver/assets/74251339/15e6ac12-0350-4873-b8ff-e4d6c6dcf28e)
<img width="335" alt="image" src="https://github.com/OpenTabletDriver/OpenTabletDriver/assets/74251339/e979b05c-a35c-4bbc-a8d0-11271458238e">

### Diagnostic Information

[Diagnostic.json](https://github.com/OpenTabletDriver/OpenTabletDriver/files/13226316/Diagnostic.json)

### Acknowledgements

- [X] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.
- [X] I am on the latest version of OpenTabletDriver.

**Comment by jamesbt365** [comment] 2023-11-01 11:24
You have the Gaomon drivers installed, this is not a supported way of using OTD.

https://github.com/X9VoiD/TabletDriverCleanup/releases/latest

Closing as duplicate of #2916 (Read FAQ next time)

**Closed by jamesbt365** 2023-11-01 11:24 UTC
Labels: support request, needs-triage
