### ISSUE TITLE
Issue with putting PC in sleep mode

### ISSUE THREAD

**Issue by Mrturtlenugget** [OpenTabletDriver/OpenTabletDriver#2428] opened 2022-09-16 12:14 UTC
I am using OTD v0.6.04 
Tablet - Gaomon s620

When I put my PC in sleep mode then turn it on OTD starts detecting then not detecting my tablet like stuttering.

**Comment by jamesbt365** [comment] 2022-09-16 12:16
Duplicate of #2365. Also use the templates in the future.

**Closed by jamesbt365** 2022-09-16 12:16 UTC
Labels: needs-triage
