### ISSUE TITLE
Support Request: Huion HS611 detected by daemon, but does not work often

### ISSUE THREAD

**Issue by kostek001** [OpenTabletDriver/OpenTabletDriver#3103] opened 2023-12-13 17:06 UTC
### What do you need help with?

Huion HS611 is detected by daemon but does not work often. For it to work, I have to disconnect it and reconnect it several times.
OS: NixOS 24.05

### What have you tried?

I found that tablet uses usbhid driver.

### Diagnostic Information

[otd.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/13663570/otd.txt)

### Acknowledgements

- [X] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.
- [X] I am on the latest version of OpenTabletDriver.

**Comment by jamesbt365** [comment] 2023-12-13 17:32
Restriction of hidsharp, duplicate of #2229.

**Closed by jamesbt365** 2023-12-13 17:32 UTC
Labels: support request, needs-triage
