### ISSUE TITLE
Relative drag / Hover disabler

### ISSUE THREAD

**Issue by crumpledmint** [OpenTabletDriver/OpenTabletDriver#1663] opened 2021-11-25 01:19 UTC
## Relative drag mode
Addon for relative mode, so you can move cursor only when dragging
Would be useful in some first person games

**Comment by gonX** [comment] 2021-12-01 00:12
[Kuuube's Hover Distance Limiter](https://github.com/Kuuuube/Hover_Distance_Limiter) does this for supported tablets (and if you're on a pre-release 0.6 version). What that can't do we can't really do either, its all up to the tablet to report hover states.

**Comment by gonX** [comment] 2021-12-01 01:20
Also closing as duplicate of #1378

**Closed by gonX** 2021-12-01 01:20 UTC
Labels: enhancement
