### ISSUE TITLE
driver not working properly

### ISSUE THREAD

**Issue by pietarus** [OpenTabletDriver/OpenTabletDriver#977] opened 2021-04-10 14:41 UTC
## Description

The driver loads the small area above the default area of the tablet, so the cursor keeps switching between the two areas making the driver unusable. 
## System Information:

| Name             | Value |
| -pietarus | ----- |
| Manjaro |
| 0.5.2.3 |
| Tablet wacom cth 480 |

**Comment by LavaDesu** [comment] 2021-04-10 14:43
https://github.com/OpenTabletDriver/OpenTabletDriver/wiki/Linux-FAQ#i-have-a-ghost-cursor-constantly-alternating-cursor-position

**Comment by X9VoiD** [comment] 2021-04-12 12:16
Duplicate of #778

**Closed by X9VoiD** 2021-04-12 12:16 UTC
Labels: bug
