### ISSUE TITLE
Area changes when switching tablet viewed

### ISSUE THREAD

**Issue by OniCado** [OpenTabletDriver/OpenTabletDriver#1558] opened 2021-10-27 00:21 UTC
## Description
When setting full area on the larger tablet, switching to view the display and area settings of the smaller tablet and then switching back, the area on the larger tablet now aligns with full area on the smaller tablet.

## System Information:

| Name                    | Value                                                                  |
| -------------------- | -------------------------------------------------- |
| Operating System | Windows 10 Pro N 21H1 Build 19043.1288       |
| OTD Version          | Dev/master latest as of 2021-10-27 19:30 UTC |
| Tablets                   | CTL-480, CTH-680                                             |

**Comment by gonX** [comment] 2021-12-01 01:12
Possibly duplicate of #1409  ?

**Comment by InfinityGhost** [comment] 2021-12-05 05:50
Definitely duplicate of #1409.

**Closed by InfinityGhost** 2021-12-05 05:50 UTC
Labels: bug
