### ISSUE TITLE
Pen doesn't work on system screens

### ISSUE THREAD

**Issue by DegFg** [OpenTabletDriver/OpenTabletDriver#1153] opened 2021-06-08 13:13 UTC
## Description
Pen and tablet button inputs do not register when these windows are in focus:
Ctrl+Alt+Del menu 
"Will you allow this app to make changes to your device?" system prompts
Task manager
Services
Device manager
Registry Editor
Most installers 
etc.

Additionally, both powershell and cmd do not affect opentablet when run normally, but do freeze tablet inputs when run with administrator privileges. The freeze also occurs when exe programs run with administrator privileges are in focus.

Other inputs sources (keyboard, regular mouse, etc) still work fine. Changing focus to a window not listed above restores tablet functionality.

## System Information:
|Open Tablet Driver 0.5.3.1|
|Wacom CTH-670 |
| Windows 10|
AMD Ryzon 5 processor
TUF B450-Plus Gaming motherboard

**Comment by X9VoiD** [comment] 2021-06-08 13:30
Duplicate of #681

**Closed by X9VoiD** 2021-06-08 13:30 UTC
Labels: bug
