### ISSUE TITLE
Huion WH1409 not detected (Manjaro)

### ISSUE THREAD

**Issue by ReturnMinusOne** [OpenTabletDriver/OpenTabletDriver#2775] opened 2023-06-07 00:06 UTC
### Steps to Reproduce

1. Launch OpenTabletDriver.
2. Plug in the WH1409 tablet.

### Expected Behavior

The tablet is detected, and its input settings can be changed.

### Observed Behavior

OpenTabletDriver sometimes reacts, but only prints the following:

```
[Detect:Info]	No tablets were detected.
[Detect:Info]	Searching for tablets...
[Detect:Info]	No tablets were detected.
[Detect:Info]	Searching for tablets...
[ArgumentOutOfRangeException:Error]	Value range is [0, 15]. (Parameter 'value')
   at HidSharp.Reports.Units.Unit.DecodeExponent(UInt32 value)
   at HidSharp.Reports.ReportDescriptor.ParseMainData(MainItemTag tag, UInt32 value)
   at HidSharp.Reports.ReportDescriptor.ParseEncodedItem(EncodedItem item)
   at HidSharp.Reports.ReportDescriptor.ParseEncodedItems(IEnumerable`1 items)
   at HidSharp.Platform.Linux.LinuxHidDevice.TryParseReportDescriptor(ReportDescriptor& parser, Byte[]& reportDescriptor)
   at HidSharp.Platform.Linux.LinuxHidDevice.RequiresGetInfo()
   at HidSharp.Platform.Linux.LinuxHidDevice.GetMaxInputReportLength()
   at OpenTabletDriver.Extensions.TryGet[TSource,TValue](TSource source, Func`2 predicate, TValue& value)
```

The last message is repeated dozens of times.

My Wacom CTE-650 tablet, on the other hand, is properly detected. The system does have issues detecting its clicks consistently however. (This may be a conflict with the libwacom driver, which I cannot uninstall as it is a dependency of libinput).

### Tablet Device

Huion WH1409

### Diagnostic Information

[opentabletrdriver-diag.zip](https://github.com/OpenTabletDriver/OpenTabletDriver/files/11671206/opentabletrdriver-diag.zip)

### Acknowledgements

- [X] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

**Comment by jamesbt365** [comment] 2023-06-07 08:54
Duplicate of #2647, #2549, #2355, #949, #870, #760, #517, #452, #408, #355 and more.

**Closed by jamesbt365** 2023-06-07 08:54 UTC
Labels: duplicate
