### ISSUE TITLE
 Add a "screen layout change" option for auxiliary buttons

### ISSUE THREAD

**Issue by RedCoder09** [OpenTabletDriver/OpenTabletDriver#3077] opened 2023-12-06 20:49 UTC
### Description

 When I was using my tablet with just the stock Huion software, I used one of my tablet buttons to cycle through screen modes. Basically, it defaulted to spanning navigation across two screens, then when I clicked the button it only spanned the left monitor, then the right, and then it came back to spanning both again. Is this possible in OTD?

### Acknowledgements

- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.
- [ ] I am on the latest version of OpenTabletDriver.

**Comment by jamesbt365** [comment] 2023-12-06 20:54
Duplicate of #2685.

In the next major version of OpenTabletDriver (0.7) there will be specific bindings to change presets, and these are already implemented on the source. However, on the current version of OpenTabletDriver you can achieve the desired behaviour by using the monitor toggle plugin which is available in the plugin manager (plugins > open plugin manager)

**Closed by jamesbt365** 2023-12-06 20:54 UTC
Labels: enhancement, needs-triage
