### ISSUE TITLE
Error: ConnectionLostException

### ISSUE THREAD

**Issue by CentFifty** [OpenTabletDriver/OpenTabletDriver#2461] opened 2022-10-20 05:07 UTC
### Acknowledgements

- [X] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

### Steps to Reproduce

1. Restart computer.
2. On startup, double click OpenTabletDriver.UX.Wpf

### Expected Behavior

Program should open, detect tablet, and work normally.

### Observed Behavior

Program opens with an error message before detecting a tablet. Pressing ok closes the entire program.

### Tablet Device

Wacom One Small

### Diagnostic Information

![Untitled](https://user-images.githubusercontent.com/95653204/196861139-39f459b7-3a6d-4b17-8fb4-0ebac80b5e8d.png)

**Comment by jamesbt365** [comment] 2022-10-20 07:04
Duplicate of many issues

**Closed by jamesbt365** 2022-10-20 07:04 UTC
Labels: bug, needs-triage
