### ISSUE TITLE
OTD not sending multi-key presses respecting user keyboard config

### ISSUE THREAD

**Issue by m10d** [OpenTabletDriver/OpenTabletDriver#2932] opened 2023-09-18 19:48 UTC
### Steps to Reproduce

1. probably required: set a system-wide key mapping, such as shown in comment below for `swapcaps`.  There is probably some unique treatment of `capslock` specifically (point B below)
1. observe/confirm system behavior: eg open an app (say, terminal) and press `ctrl + minus`.  Observe it zoom out.
2. configure a side-button via OTD to be `ctrl + minus` (via the auto-detect of keypress - the result: 
![otd - multi key binding issue](https://github.com/OpenTabletDriver/OpenTabletDriver/assets/59897595/deb9cb47-9b9d-48a9-906a-2d1ee8142b57)
3. apply & focus on same test/system app; press the configured key
4. observe just the `=` being typed, implying that `ctrl` was not successfully conveyed.

I believe the issue here is that OTD is not respecting my keyboard config (`setxkbmap -option caps:swapecaps`).  So above, I press "control" but the physical key is labeled "CapsLock" on my kbd, and the kbd is indeed sending a 58 (per `xev`).

I am not familiar with how these keycodes get processed - but **every** other app I've used obeys the system key mapping - I imagine under the hood this just means OTD is grabbing it prior/below the intended translation layer.

Further, this isn't trivial to work around because: 

a) it wasn't at all obvious what was wrong at first
b) I _**cannot press the equivalent pre-map keycode**_ - in OTD, I can't press "capslock" in combination with anything, this is the closest I can get: 
![otd capslock key binding](https://github.com/OpenTabletDriver/OpenTabletDriver/assets/59897595/5de81de5-516e-46cc-9bd0-9e9b59b88c2f)

ubuntu 22.04, wayland, caps swapped via `setxkbmap`, or persisted across boots with `/etc/default/keyboard`: 
```
$ cat /etc/default/keyboard
# KEYBOARD CONFIGURATION FILE

# Consult the keyboard(5) manual page.

XKBMODEL="pc105"
XKBLAYOUT="us"
XKBVARIANT=""
XKBOPTIONS="ctrl:swapcaps"

BACKSPACE="guess"
```

### Expected Behavior

pressing the key works as `ctrl-` modified would be expected to

### Observed Behavior

`ctrl` mod is missing

### Tablet Device

NA but huion 12

### Diagnostic Information

<too large for github>

### Acknowledgements

- [X] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

**Comment by jamesbt365** [comment] 2023-09-18 19:49
Duplicate of #1821.

**Closed by jamesbt365** 2023-09-18 19:49 UTC
Labels: bug, needs-triage
