### ISSUE TITLE
Cursor wont move when using Relative mode

### ISSUE THREAD

**Issue by Luminat3** [OpenTabletDriver/OpenTabletDriver#2114] opened 2022-03-11 08:38 UTC
## Description

I have a CTL-472 and when i tried to switch to relative mode the cursor wont move, i dont know why
## System Information:

| Luminat3            | Value |
| ---------------- | ----- |
| Operating System Windows 10         |
| OpenTabletDriver Version v0.6.0.3 |
| Tablet  CTL-472                 |

**Comment by jamesbt365** [comment] 2022-03-11 08:49
duplicate of #2061

**Closed by jamesbt365** 2022-03-11 08:49 UTC
Labels: bug
