### ISSUE TITLE
Veikk a15 pro not detected

### ISSUE THREAD

**Issue by DrunkenMasterTim** [OpenTabletDriver/OpenTabletDriver#2210] opened 2022-04-23 22:01 UTC
# Support Request

**Comment by jamesbt365** [comment] 2022-04-23 22:21
Duplicate of #2136 

One, you need to fill out the template, 2, you have ALREADY made multiple issues for the same problem, if you want it checked more often come down to the discord and stop making new issues. I have told you before not to do this.

**Closed by jamesbt365** 2022-04-23 22:21 UTC
Labels: support request
