### ISSUE TITLE
Support Request: Auxiliary buttons not working on Deco 01 v2

### ISSUE THREAD

**Issue by 8ryo** [OpenTabletDriver/OpenTabletDriver#1661] opened 2021-11-22 22:23 UTC
As title says, the auxiliary buttons aren't working on the XP-Pen Deco 01 v2.

![image](https://user-images.githubusercontent.com/58891125/142942615-38497513-f085-4e76-af7e-dc4dc9c532d0.png)

All 8 buttons are reporting 1 through to 128 in the tablet debugger

I've tried different output modes (e.g. Absolute, windows ink absolute etc. ), nothing has worked. Also restarted my pc to see if it would work, to no avail. 

Tried it with all plugins disabled, still doesn't work.

Seems like a configuration issue but someone else would have brought up this bug by now so I'm gonna presume there's something wrong on my end.

Here's my config:

![image](https://user-images.githubusercontent.com/58891125/142943449-2f5bcfae-f683-42ed-97d4-ba2014e58674.png)

![image](https://user-images.githubusercontent.com/58891125/142943477-b0662dba-1a51-4b35-9fc2-bea9fb10375f.png)

I have script runner and OEM kill enabled

**Comment by jamesbt365** [comment] 2021-11-22 22:25
Please export a diagnostic for me. Help > export diagnostics, save that file and attach it here as a txt file.

**Comment by 8ryo** [comment] 2021-11-22 22:51
[Deco 01 v2.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/7584830/Deco.01.v2.txt)

mb it probably said to do that earlier, here you go

**Comment by Mrcubix** [comment] 2021-11-22 23:20
let's do something simple, go to `Tablet > Tablet debugger`, there press one of your button, if on the right it say aux and then show all 8 buttons then the tablet send the data as intended, if not then a parser modification is required

**Comment by 8ryo** [comment] 2021-11-22 23:32
> * if on the right side, it say aux and then show all 8 keys then the tablet send the data as intended,

You can see it in the top screenshot, it doesn't say aux, it shows 1,2,4,8,16... for all buttons 1-8 respectively in the position part on the tablet report.

![image](https://user-images.githubusercontent.com/58891125/142950352-f7d24c16-e703-4560-b3f5-8099c6eccd83.png)

This is me pressing the very top button on the tablet

**Comment by 8ryo** [comment] 2021-11-22 23:33
It seems to be reporting back button presses as positions on the tablet as far as I can tell

**Comment by 8ryo** [comment] 2021-11-23 00:02
Raw tablet data from each button press, 0 degrees orientation, going from top to bottom:

02 F0 01
02 F0 02
02 F0 04
02 F0 08
02 F0 10
02 F0 20
02 F0 40
02 F0 80

**Comment by 8ryo** [comment] 2021-11-23 00:06
And then tablet report shows for each button press respectively:

Position: [1,0]
Position: [2,0]
Position: [4,0]
Position: [8,0]
Position: [16,0]
Position: [32,0]
Position: [64,0]
Position: [128,0]

ReportID: 0 
Pressure: 0
PenButtons: [False, False]

These last 3 remain for all button presses

**Comment by gonX** [comment] 2021-11-23 00:27
I gave this a quick look, some quick notes:

- This is fixed on master, so if using a pre-release version is fine with you (note that plugin support is spotty), that is an option.
- For any helpers reading: the XP Pen parser in 0.5.3 does not support aux reports from this tablet, so simply changing the parser won't fix it. A parser backport of some sort is needed - might be possible with Cubix' Backports, but not immediately from what I can see.

Alternatively you can wait for OTD 0.6 to come out, though there is no release date set yet.

**Comment by Mrcubix** [comment] 2021-11-23 12:50
what does the first and second bytes become when dragging and when out of range?

**Comment by Mrcubix** [comment] 2021-11-23 13:15
[OTD.Backport.zip](https://github.com/OpenTabletDriver/OpenTabletDriver/files/7588177/OTD.Backport.zip)

- drag and drop this in `Plugin > Plugin manager`, then head to the tool tab > OTD.Backport > tick enable, then save
- `Tablets > Detect tablet` and now buttons should work

**Comment by 8ryo** [comment] 2021-11-23 16:18
I installed the plugin, didn't work on 0.4.1.0 or 0.5.3.3

**Comment by jamesbt365** [comment] 2021-11-23 16:19
Make sure you do it on 0.5.3.3 and export a diag with help > export diagnostics if it doesn't work

**Comment by Mrcubix** [comment] 2021-11-23 18:06
this plugin doesn't touch the tablet at all, only configurations , and parsers from those who need it

**Comment by 8ryo** [comment] 2021-11-23 20:16
Ok kinda weird, I managed to reproduce the issue 2-3 times before but now I can't reproduce it for some reason. Either way, the buttons still don't work unfortunately

**Comment by Mrcubix** [comment] 2021-11-23 20:18
go to the tablet debugger and press them, check if they appear on the right side

**Comment by 8ryo** [comment] 2021-11-23 20:21
Yeah there is a response but they appear as positions like before

Position: [1,0]
Position: [2,0]
Position: [4,0]
Position: [8,0]
Position: [16,0]
Position: [32,0]
Position: [64,0]
Position: [128,0]

**Comment by Mrcubix** [comment] 2021-11-23 20:24
that's abnormal for sure, the second byte is F0 and has the 5 byte set, which should press the button, Check the second byte when dragging and when out of range

**Comment by 8ryo** [comment] 2021-11-23 20:31
Hover:

![image](https://user-images.githubusercontent.com/58891125/143098892-33f11b34-34e9-4f40-b8c7-f8131eb9df1f.png)

Drag:

![image](https://user-images.githubusercontent.com/58891125/143098992-3a74f7eb-6626-4a95-9def-8453948f2865.png)

Out of range: 

![image](https://user-images.githubusercontent.com/58891125/143099083-ee2b1476-b700-42d2-b5ba-2d1bfdc02fbd.png)


Bottom pen button will show A2/A3 for hover/drag respectively

Top pen button will show A4/A5 for hover/drag respectively

**Comment by 8ryo** [comment] 2021-11-23 20:33
And then for the tablet buttons it's the same as before: 
02 F0 01
02 F0 02
02 F0 04
02 F0 08
02 F0 10
02 F0 20
02 F0 40
02 F0 80

**Comment by Mrcubix** [comment] 2021-11-23 20:36
send the the tablet config you'll find in `Configurations\XP-Pen\Deco 01 V2.json`

**Comment by 8ryo** [comment] 2021-11-23 20:37
[Deco 01 V2.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/7590887/Deco.01.V2.txt)

**Comment by Mrcubix** [comment] 2021-11-23 20:39
- tool > OTD.BackPort > tick enable > tick force apply > save > untick force apply 
- `Tablets > Detect tablet`

**Comment by 8ryo** [comment] 2021-11-23 20:41
My tablet has stopped working

**Comment by Mrcubix** [comment] 2021-11-23 20:42
export a diagnostic file

**Comment by 8ryo** [comment] 2021-11-23 20:42
[diag.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/7590923/diag.txt)

**Comment by Mrcubix** [comment] 2021-11-23 20:45
- first, i told you to untick force apply in the tool,
- second, nothing in the diag indicate that it stop working in any way
- third, `Tablet > Tablet debugger`, press aux keys, see if they appear on the right, also move your pen, a blue dot should appear in the visualizer

**Comment by 8ryo** [comment] 2021-11-23 20:50
Ok can you check this diag to see if I'm doing anything wrong this time:
[diag2.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/7590940/diag2.txt)

This is my screen now:
![image](https://user-images.githubusercontent.com/58891125/143114414-0d5be107-1366-44a8-b699-086b155baf85.png)

**Comment by Mrcubix** [comment] 2021-11-23 20:53
`Tablet > device string reader` > type the following:

- 10429
- 2309

then presse dump all and upload that here

**Comment by 8ryo** [comment] 2021-11-23 20:58
[stringdump.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/7590987/stringdump.txt)

**Comment by Mrcubix** [comment] 2021-11-23 21:04
[OTD.Backport.zip](https://github.com/OpenTabletDriver/OpenTabletDriver/files/7591002/OTD.Backport.zip)

- uninstall OTD.Backport via the plugin manager, 
- install this new version
- Go to Tool > OTD.Backport > tick enable and force apply > save > untick force apply
- `Tablet > Detect tablet`

**Comment by 8ryo** [comment] 2021-11-23 21:12
The cursor is stuck in the top left corner of the screen for both hover/drag
[diag.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/7591053/diag.txt)
.

**Comment by Mrcubix** [comment] 2021-11-23 21:15
[Deco 01 V2.zip](https://github.com/OpenTabletDriver/OpenTabletDriver/files/7591062/Deco.01.V2.zip)
place the json file inside of the archive in `Configurations\XP-Pen` replace the old one when asked, then re-detect

**Comment by 8ryo** [comment] 2021-11-23 21:36
ok pen works but only bottom half of tablet area is detected, tablet buttons sends the cursor down to bottom left
[diag.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/7591136/diag.txt)

this is when i hover about 2/3 from the top of the drawing area
![image](https://user-images.githubusercontent.com/58891125/143132997-1aa93707-0721-401e-a443-fb593a72bef6.png)

**Comment by Mrcubix** [comment] 2021-11-23 21:37
try to get maximum position by moving to the bottom right of the tablet

**Comment by 8ryo** [comment] 2021-11-23 21:38
yeah i can get there no issue, its aligned properly there

**Comment by Mrcubix** [comment] 2021-11-23 21:39
i should had added that i need the value

**Comment by 8ryo** [comment] 2021-11-23 21:40
02 A0 00 00 ...

**Comment by Mrcubix** [comment] 2021-11-23 21:40
i do not need raw value, i need the value on the right where it say Position

**Comment by 8ryo** [comment] 2021-11-23 21:41
[0, 0]

**Comment by 8ryo** [comment] 2021-11-23 21:42
oh mb i have it left handed

**Comment by 8ryo** [comment] 2021-11-23 21:43
[50791, 31750] that's as far as i can get it

**Comment by 8ryo** [comment] 2021-11-23 21:45
Do you have the old json, it might have been area refresh issue, the driver sometimes messes up the drawing area

**Comment by Mrcubix** [comment] 2021-11-23 21:48
[Deco 01 V2.zip](https://github.com/OpenTabletDriver/OpenTabletDriver/files/7591206/Deco.01.V2.zip)
use this config, after re-plugging your tablet ,you should be able to use it entirely

**Comment by 8ryo** [comment] 2021-11-23 21:50
yeah the full area works now

**Comment by Mrcubix** [comment] 2021-11-23 21:55
aux keys shoud also work, check that

**Comment by 8ryo** [comment] 2021-11-23 21:55
no unfortunately, still sends the cursor down to the bottom left

**Comment by 8ryo** [comment] 2021-11-23 21:58
but there is a response which is a good sign I suppose

**Comment by Mrcubix** [comment] 2021-11-23 22:03
you mean top left, but anyway

`Tablet > Tablet debugger` and i assume that when you press an aux key, no aux key array appear on the right?

which is weird because when you press an aux key, you state it's `F0` which convert to `11110000` which mean the bit at index 4 (5th bit) is set (= 1)

**Comment by 8ryo** [comment] 2021-11-23 22:05
![image](https://user-images.githubusercontent.com/58891125/143136595-793120e9-64dc-43c0-b45c-d9cbe06dc0e4.png)

This is when I press a tablet button

**Comment by Mrcubix** [comment] 2021-11-23 22:07
send the deco 01 config you have rn

**Comment by 8ryo** [comment] 2021-11-23 22:09
[Deco 01 V2.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/7591276/Deco.01.V2.txt)

[diag.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/7591280/diag.txt)

**Comment by Mrcubix** [comment] 2021-11-23 22:13
[OTD.Backport-dll.zip](https://github.com/OpenTabletDriver/OpenTabletDriver/files/7591290/OTD.Backport-dll.zip)

close OTD, head to `%localappdata%/opentabletdriver/Plugins/OTD.Backport` and extract the zip file there, replace the dll when ask, start OTD again and everything should work

**Comment by 8ryo** [comment] 2021-11-23 22:17
Works initially but when button is pressed, tablet is no longer detected

**Comment by Mrcubix** [comment] 2021-11-23 22:19
export a diag

**Comment by 8ryo** [comment] 2021-11-23 22:19
[diag.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/7591319/diag.txt)

**Comment by Mrcubix** [comment] 2021-11-23 22:20
i need a diag after the issue actually happen, don't restart OTD

**Comment by 8ryo** [comment] 2021-11-23 22:21
[diag.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/7591325/diag.txt)

**Comment by Mrcubix** [comment] 2021-11-23 22:23
this is pressing aux keys right?

**Comment by 8ryo** [comment] 2021-11-23 22:23
yep

**Comment by Mrcubix** [comment] 2021-11-23 22:34
[OTD.Backport-dll.zip](https://github.com/OpenTabletDriver/OpenTabletDriver/files/7591386/OTD.Backport-dll.zip)

close OTD, replace the DLL in `%localappdata%/opentabletdriver/Plugins/OTD.Backport`

start OTD again, press the any aux key, export a diag

**Comment by 8ryo** [comment] 2021-11-23 22:41
[diag.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/7591400/diag.txt)

Tablet not detected when aux button is pressed still

**Comment by Mrcubix** [comment] 2021-11-23 22:52
Alright, last thing i'm gonna check is how busted this tablet is, do the following when you got time later,

Original config so you can play: [Deco 01 V2.zip](https://github.com/OpenTabletDriver/OpenTabletDriver/files/7591438/Deco.01.V2.zip)

# Steps: 

- https://desowin.org/usbpcap/thankyou.html?file=1.5.4.0/USBPcapSetup-1.5.4.0.exe Download and install this tool

- When done, head to C:\Program Files\USBPcap in the explorer (you can probably copy paste that path in the path bar)

- Once you're there, start USBPcapCMD.exe

- A console will appear, answer n at the first prompt and reboot your pc

- Head back to C:\Program  Files\USBPcap,

- Start USBPcapCMD.exe,

- screenshot the console.

**Comment by 8ryo** [comment] 2021-11-23 23:02
Alright, thanks for the help so far 👍

**Comment by 8ryo** [comment] 2021-12-05 17:55
Ok the Aux buttons are working now but there's an issue with the draw area sizing. I'll close this issue and open a new one.

**Comment by 8ryo** [comment] 2021-12-05 18:08
Nm, the OTD backport doesn't work when Windows Ink is enabled. But in the meantime, I wonder if anyone has a good combination of plugins which is similar to or better than Windows Ink in terms of writing/drawing.

**Comment by Mrcubix** [comment] 2021-12-05 18:14
Windows ink won't affect the backported configurations and parser in any ays at all

**Comment by 8ryo** [comment] 2021-12-05 18:19
I mean, when I enable Windows Ink, the aux buttons just stop working but it's honestly up to you if you want to look into the issue. I'm fine using Absolute Mode instead of the Windows Ink version, I just need help with getting a good combination of plugins for drawing/writing tbh

**Comment by Mrcubix** [comment] 2021-12-05 18:20
ah, you would need script runner and ahk to make use of aux in Windows Ink Mode

**Comment by 8ryo** [comment] 2021-12-05 18:22
So I need to make a separate script for each key essentially?

**Comment by Mrcubix** [comment] 2021-12-05 18:23
Yes, the only downside, but you'll be able to do anything using it.

**Comment by 8ryo** [comment] 2021-12-05 18:24
Yeah it's not too bad, I was using scripts for some of the keys anyways so not a huge deal

**Comment by 8ryo** [comment] 2021-12-05 18:54
Ok the only thing that isn't working now is the Windows Ink pen tip. If the pen tip is bound to Windows Ink Pen tip, the tablet is no longer detected whenever you touch the tablet with the pen.

I have installed Vmulti along with the Windows Ink plugin.

[diag.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/7656589/diag.txt)

**Comment by Mrcubix** [comment] 2021-12-05 18:59
Make sure you're using the Windows ink pen tip in Windows ink mode

**Comment by 8ryo** [comment] 2021-12-05 19:08
Oh yeah it's working now. Btw how do you reopen OTD? Double-clicking the tray icon doesn't work for some reason.

**Comment by jamesbt365** [comment] 2021-12-05 19:08
If double clicking doesn't work then just right click it.

**Comment by 8ryo** [comment] 2021-12-05 19:09
No that doesn't work either

**Comment by jamesbt365** [comment] 2021-12-05 19:09
Windows moment.

**Comment by 8ryo** [comment] 2021-12-05 19:09
![image](https://user-images.githubusercontent.com/58891125/144760126-09a0a9d3-b82b-4f12-a0ff-e93fd59f1904.png)

**Comment by 8ryo** [comment] 2021-12-05 19:10
Bottom right is OTD

**Comment by jamesbt365** [comment] 2021-12-05 19:10
just kill it in task manager and reopen it then. Windows is weird.

**Comment by Mrcubix** [comment] 2021-12-05 19:10
![image](https://user-images.githubusercontent.com/39861216/144760152-696844e6-5f96-412a-8176-d8d195572460.png)
it should appear as such, if not then something broke

**Comment by 8ryo** [comment] 2021-12-05 19:11
Right click doesn't do anything for me unfortunately

**Comment by 8ryo** [comment] 2021-12-05 19:11
oh minimised give me a sec

**Comment by 8ryo** [comment] 2021-12-05 19:13
Yeah.. doesn't work. Btw minimise and close both do the same thing for me, they both put the application in the system tray

**Comment by Mrcubix** [comment] 2021-12-05 19:15
Closing the application, only kill both process on stable.
Minimizing is the only thing that can make it go to the system tray.

**Comment by 8ryo** [comment] 2021-12-05 19:15
Yeah closing the application doesn't kill it for me for some reason

**Comment by 8ryo** [comment] 2021-12-05 19:17
But the issue still remains, I still can't access the application via system tray, it just comes up as 2 blank boxes which is weird

**Comment by jamesbt365** [comment] 2021-12-05 19:19
`TASKKILL /F /IM OpenTabletDriver.UX.Wpf.exe
TASKKILL /F /IM OpenTabletDriver.Daemon.exe`

**Comment by 8ryo** [comment] 2021-12-05 19:20
where do I enter this command?

**Comment by jamesbt365** [comment] 2021-12-05 19:21
cmd

**Comment by 8ryo** [comment] 2021-12-05 19:22
oh I suppose I can put the commands into a .bat and run it like that?

**Comment by jamesbt365** [comment] 2021-12-05 19:23
or you could just run each indivdually?

**Comment by jamesbt365** [comment] 2021-12-05 19:23
just throw each into cmd and press enter, one at a time.

**Comment by Mrcubix** [comment] 2021-12-16 23:05
this will be fixed in the next release of OTD.Backport, something something, OTD not liking more than 8 buttons at once in stable.

**Comment by 8ryo** [comment] 2021-12-20 17:05
Repeatedly moving the pen in and out of detection range causes the aux buttons to be triggered. Don't know if this is to do with the backport though.

**Comment by 8ryo** [comment] 2021-12-20 17:08
[diag.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/7746882/diag.txt)

**Comment by Mrcubix** [comment] 2021-12-20 18:10
fixed in master and [OTD.BackPort](https://github.com/Mrcubix/OTD.Backport/releases/tag/1.0.2)

**Closed by Mrcubix** 2021-12-20 18:10 UTC
Labels: support request
