### ISSUE TITLE
Add support for Wacom One Small CTCW1AB

### ISSUE THREAD

**Issue by BZ92** [OpenTabletDriver/OpenTabletDriver#3105] opened 2023-12-14 01:55 UTC
### Manufacturer

Wacom

### Product Name

CTCW1AB small

### Additional Information

I have the CTL-472 and after I bought the CTCW1AB small I realized it is not supported with open tablet drivers.

### Diagnostic Information

[diagnostic.json](https://github.com/OpenTabletDriver/OpenTabletDriver/files/13667311/diagnostic.json)

### Acknowledgements

- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

**Comment by jamesbt365** [comment] 2023-12-14 11:42
Duplicate of #3101, which is a duplicate of #2993, which is fixed in #2902

Also no idea how you got that model name because its not the name, or why you didn't fill out any of the information we asked for except for the diagnostic file, when we ask you to provide information for *us* to do something for you, its nice for you to help us help you by providing us with what we asked for. Those boxes aren't there for show.

**Closed by jamesbt365** 2023-12-14 11:42 UTC
Labels: duplicate, configuration
