### ISSUE TITLE
Mouse wheel scrolling support

### ISSUE THREAD

**Issue by RagingLightning** [OpenTabletDriver/OpenTabletDriver#1496] opened 2021-10-09 15:19 UTC
## Description
I recently switched to this driver fron the hawku one and love it, however:

One thing I'm missing is the ability to map a pen button to something like "VSCROLL" in hawku where tablet input would (also) be interpreted as rotation of the mouse wheel while the button is held down.

Ideally there would also be the option to switch the direction the scrolling is mapped (pen up > scroll up vs pen up > scroll down)

**Comment by X9VoiD** [comment] 2021-10-09 15:23
Duplicate of #1158

**Closed by X9VoiD** 2021-10-09 15:23 UTC
Labels: enhancement
