### ISSUE TITLE
an ArgumentOutOfRangeException:Error with huion H580X

### ISSUE THREAD

**Issue by KaziiTheAvali** [OpenTabletDriver/OpenTabletDriver#2549] opened 2022-12-24 16:29 UTC
### Acknowledgements

- [X] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

### Steps to Reproduce

plug in huionH580X with the opentabletdriver open

### Expected Behavior

should of connected after a replug

### Observed Behavior

a load of the same error message ([ArgumentOutOfRangeException:Error]	Value range is [0, 15]. (Parameter 'value')

### Tablet Device

HuionH580X

### Diagnostic Information

[help.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/10298884/help.txt)

**Comment by jamesbt365** [comment] 2022-12-24 16:30
duplicate of many issues. Its covered on the wiki to. This is not a bug.

**Closed by jamesbt365** 2022-12-24 16:30 UTC
Labels: bug, needs-triage
