### ISSUE TITLE
Click and tap feature like wacom driver if possible

### ISSUE THREAD

**Issue by enesaltinkaya** [OpenTabletDriver/OpenTabletDriver#3482] opened 2024-09-28 12:52 UTC
### Description

Say you are using blender and using a pen button to pan around an object.  
When the button is triggered while the pen is not touching the tablet, movements are not accurate.  
It would be very nice if the pen button triggers only when the pen is touching the tablet.  
Like they do in the wacom driver.  

![image](https://github.com/user-attachments/assets/5a6a58f7-9bdf-410e-958b-d9869e231544)

### Acknowledgements

- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.
- [X] I am on the latest version of OpenTabletDriver.

**Comment by jamesbt365** [comment] 2024-09-28 12:53
> [x] I have searched the existing issues and this new issue is not a duplicate of any.

![image](https://github.com/user-attachments/assets/a35c0954-3eeb-4f49-960e-4f8a8adca183)

Blatant duplicate of #3165.

**Closed by jamesbt365** 2024-09-28 12:53 UTC
Labels: enhancement, needs-triage

**Comment by enesaltinkaya** [comment] 2024-09-28 13:00
Obviously that that ticket will sit there for years to come.

Good to ask once a year :+1:
