### ISSUE TITLE
10moon 1060N

### ISSUE THREAD

**Issue by ghost** [OpenTabletDriver/OpenTabletDriver#3349] opened 2024-06-29 11:53 UTC
### Manufacturer

10moon 

### Product Name

1060N

### Device Width

10 inch

### Device Height

6 inch

### Pressure Levels

8192

### Lines per Inch (LPI)

5080

### Additional Information

In the tablet support page, it mentions features that my tablet doesn't seem to have. My tablet isn't working exactly right. The cursor moves fine, but I can't click or select things with either the pen or mouse. However, sometimes it works the other way around: I can click but can't write or draw with the pen. (In order to write something, I have to lift the pen from the tablet, which only leaves a dot or a straight line on the screen.)

It looks like there might be a mismatch with the device name. According to the Official Technical Documentation (OTD), it's identified as a 10moon 1060N, but the tablet itself says Mezzrow 1060VIN. I can't find any information about Mezzrow, but searching for 10moon 1060N shows a similar device.

### Diagnostic Information

[Diagnostic Information.txt](https://github.com/user-attachments/files/16039856/Diagnostic.Information.txt)

### Acknowledgements

- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

**Comment by jamesbt365** [comment] 2024-06-29 12:04
Duplicate of #3331, and #3176. There are multiple proposed PRs to "fix" this, see #2615 and #2853.

**Closed by jamesbt365** 2024-06-29 12:04 UTC
Labels: duplicate, invalid, support request
