### ISSUE TITLE
Add support for Viewsonic Woodpad 10 PF1030

### ISSUE THREAD

**Issue by shinysquirrel04** [OpenTabletDriver/OpenTabletDriver#3466] opened 2024-09-15 19:53 UTC
### Manufacturer

Viewsonic

### Product Name

Woodpad 10 PF1030

### Device Width

224 mm

### Device Height

140 mm

### Pressure Levels

4096

### Lines per Inch (LPI)

5080

### Diagnostic Information

[opentabletdriver-diagnostics.json](https://github.com/user-attachments/files/17007204/opentabletdriver-diagnostics.json)

### Acknowledgements

- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

**Comment by jamesbt365** [comment] 2024-09-15 19:54
Duplicate of #3040.

**Closed by jamesbt365** 2024-09-15 19:53 UTC
Labels: configuration, needs-triage
