### ISSUE TITLE
Add support for huion H951P

### ISSUE THREAD

**Issue by YANGhww** [OpenTabletDriver/OpenTabletDriver#3451] opened 2024-09-02 11:52 UTC
### Manufacturer

huion

### Product Name

H951P

### Device Width

180

### Device Height

300

### Pressure Levels

8192

### Lines per Inch (LPI)

5080

### Additional Information

[Detect:Info]	No tablets were detected.

### Diagnostic Information

[huion H951P.json](https://github.com/user-attachments/files/16837052/huion.H951P.json)

### Acknowledgements

- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

**Comment by jamesbt365** [comment] 2024-09-02 11:54
>  I have searched the existing issues and this new issue is not a duplicate of any.

Duplicate of #3445, #3290 and already resolved with #2927.

> I have written a concise and meaningful title.

You certainly didn't.

**Closed by jamesbt365** 2024-09-02 11:54 UTC
Labels: configuration
