### ISSUE TITLE
Add support for Parblo N4

### ISSUE THREAD

**Issue by Buzzie3** [OpenTabletDriver/OpenTabletDriver#2812] opened 2023-06-25 17:53 UTC
### Manufacturer

parblo 

### Product Name

n4

### Device Width

101.6

### Device Height

76.2

### Pressure Levels

8192

### Lines per Inch (LPI)

5080 

### Additional Information

You can add support for parblo n4 without OTD is not pleasant to play on it

### Diagnostic Information

1

### Acknowledgements

- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

**Comment by X9VoiD** [comment] 2023-06-25 17:55
Duplicate of #2756

**Closed by X9VoiD** 2023-06-25 17:55 UTC
Labels: configuration

**Comment by Keyunge** [comment] 2025-07-24 13:44
The same problem, down to the pixel

**Comment by Keyunge** [comment] 2025-07-24 13:44
The same problem, down to the pixel
