### ISSUE TITLE
Sort the filters by name, please!🆘

### ISSUE THREAD

**Issue by Iluvenis** [OpenTabletDriver/OpenTabletDriver#3236] opened 2024-03-11 01:00 UTC
### Description

![image](https://github.com/OpenTabletDriver/OpenTabletDriver/assets/12654953/1011adf5-a402-4cee-82e5-60b2b58c6d36)
The filters are not sorted, I can't quickly find the filter I need, please add a sort.

### Acknowledgements

- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.
- [X] I am on the latest version of OpenTabletDriver.

**Comment by jamesbt365** [comment] 2024-03-11 01:04
Duplicate of #1972 and #2223.

**Closed by jamesbt365** 2024-03-11 01:04 UTC
Labels: enhancement
