### ISSUE TITLE
OpenTabletDriver.Daemon.exe run in tray

### ISSUE THREAD

**Issue by miyuki-ts** [OpenTabletDriver/OpenTabletDriver#3332] opened 2024-06-02 09:26 UTC
### Description

be able to run the OpenTabletDriver.Daemon.exe in tray, so i can minimize it, without it are on my process bar for terminal. and can open it again through clicking on the icon in tray.

### Acknowledgements

- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.
- [X] I am on the latest version of OpenTabletDriver.

**Comment by jamesbt365** [comment] 2024-06-02 11:29
Duplicate of #3079.

**Closed by jamesbt365** 2024-06-02 11:29 UTC
Labels: duplicate, enhancement
