### ISSUE TITLE
Theme

### ISSUE THREAD

**Issue by Miyuki-10** [OpenTabletDriver/OpenTabletDriver#3247] opened 2024-03-13 23:19 UTC
### Description

Add a button or somewhere an user can select theme, such as dark or black theme so there is more than just the default white theme, or a theme to have design simplistic. But i think dark and black theme would me enough.

### Acknowledgements

- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.
- [X] I am on the latest version of OpenTabletDriver.

**Comment by jamesbt365** [comment] 2024-03-13 23:27
Duplicate of #3127, #1740, #1245 & more.

Fixed in #2772 or post merge of #2772.

**Closed by jamesbt365** 2024-03-13 23:27 UTC
Labels: enhancement, needs-triage
