### ISSUE TITLE
Laggy cursor

### ISSUE THREAD

**Issue by TimStep** [OpenTabletDriver/OpenTabletDriver#2301] opened 2022-06-09 19:16 UTC
### Acknowledgements

- [x] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

### Steps to Reproduce

The issue is there from the first connection

https://user-images.githubusercontent.com/52534508/172925152-7d6e3365-4f35-4a4a-bf31-ee4256652591.mp4

t

### Expected Behavior

Cursor functioning normally

### Observed Behavior

The cursor is lagging

### Tablet Device

XP-Pen Star 06C

### Diagnostic Information

https://pastebin.com/iFYDGPf7

**Comment by jamesbt365** [comment] 2022-06-09 19:18
same boat as #2245, need a pcap on windows

**Comment by jamesbt365** [comment] 2022-06-09 19:23
going to close as a duplicate of #2245, anything should go there

**Closed by jamesbt365** 2022-06-09 19:23 UTC
Labels: bug
