### ISSUE TITLE
Can´t add Plugins

### ISSUE THREAD

**Issue by EnricoCMD** [OpenTabletDriver/OpenTabletDriver#979] opened 2021-04-11 16:13 UTC
When I click on the button to open that nothing happens...a friend has the same issue

**Comment by X9VoiD** [comment] 2021-04-11 16:14
Are you getting a warning about running as admin?

**Comment by EnricoCMD** [comment] 2021-04-11 16:17
> 
> 
> Are you getting a warning about running as admin?

yes but i do not run this with admin

**Comment by X9VoiD** [comment] 2021-04-11 16:20
Duplicate of #943

**Closed by X9VoiD** 2021-04-11 16:20 UTC
