### ISSUE TITLE
XP-Pen G430 not detected

### ISSUE THREAD

**Issue by Kirass0** [OpenTabletDriver/OpenTabletDriver#898] opened 2021-03-21 05:25 UTC
## Description

Hi, my tablet is not being detected. It's XP-Pen G430 bought in 2016.
[diagnostics.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/6176894/diagnostics.txt)

## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System | Windows 10
| Software Version | 0.5.2.3
| Tablet           | XP-Pen G430

**Comment by X9VoiD** [comment] 2021-03-21 05:29
Do you have another driver installed? This G430 is missing a HID endpoint.

**Comment by Kirass0** [comment] 2021-03-21 05:37
Currently I have original drivers installed, but even without them OTD wasn't detecting it.
Should I uninstall and then export diagnostics again?

**Comment by X9VoiD** [comment] 2021-03-21 05:39
Check if you have an installed program called "WinUSB", uninstall that if it's there, and then re-export diagnostics.

**Comment by Kirass0** [comment] 2021-03-21 05:48
Driver uninstalled. I didn't find anything like "WinUSB" in programs list.
[diagnostics.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/6176914/diagnostics.txt)

**Comment by X9VoiD** [comment] 2021-03-21 05:52
Unfortunately this G430 don't have an explicit vendor endpoint to communicate with. It cannot be supported on Windows reliably as Windows itself exclusively opens the handle to the device.

**Comment by InfinityGhost** [comment] 2021-03-22 00:57
> Unfortunately this G430 don't have an explicit vendor endpoint to communicate with. It cannot be supported on Windows reliably as Windows itself exclusively opens the handle to the device, leaving us with no way to access it.

Pretty sure this is also a duplicate of a previous attempt to get a G430 working with this issue.

**Closed** 2021-03-23 02:54 UTC
Labels: bug, configuration, wontfix
