### ISSUE TITLE
HawkuFilters Smoothing

### ISSUE THREAD

**Issue by colorgrey** [OpenTabletDriver/OpenTabletDriver#1766] opened 2021-12-19 12:44 UTC
## Description

Sometimes when I turn on smoothing from the "HawkuFilters" plugin and set it to anything other than 0ms my cursor sometimes freezes. I don't know if it is the driver or not because I replug the tablet and restart the driver but it still freezes.

## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System         | macOS Mojave 10.14.6
| OpenTabletDriver Version | v0.5.3.3
| Tablet                   | CTL-472

**Comment by jamesbt365** [comment] 2022-02-13 22:27
Is this caused from your cpu jumping high?

**Comment by jamesbt365** [comment] 2022-07-28 19:34
If so its likely going to be resolved by #2342

**Comment by InfinityGhost** [comment] 2022-07-29 00:49
Definitely related to #2342

**Comment by gonX** [comment] 2022-11-07 16:10
Indirect duplicate of #473

**Closed by gonX** 2022-11-07 16:10 UTC
Labels: support request
