### ISSUE TITLE
Add support for H951P

### ISSUE THREAD

**Issue by Layla-Lux** [OpenTabletDriver/OpenTabletDriver#3445] opened 2024-08-26 18:24 UTC
### Manufacturer

Huion

### Product Name

Huion Insiroy 2M

### Device Width

306mm

### Device Height

180 x 7.5~9.5mm

### Pressure Levels

8192

### Diagnostic Information

[Diagnostic's.json](https://github.com/user-attachments/files/16752288/Diagnostic.s.json)

### Acknowledgements

- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

**Comment by jamesbt365** [comment] 2024-08-26 18:25
Duplicate of #3290, already supported as of #2927.

**Closed by jamesbt365** 2024-08-26 18:25 UTC
Labels: configuration, needs-triage
