### ISSUE TITLE
Gaomon s56k not being detected

### ISSUE THREAD

**Issue by EikelFlo** [OpenTabletDriver/OpenTabletDriver#1299] opened 2021-07-30 14:20 UTC
## What I've already tried
WinUSBCleanup

## Diagnostic Information
https://gist.github.com/EikelFlo/6efba32923735b79c6fad9ffa1c1c42e

**Comment by Mrcubix** [comment] 2021-07-30 14:23
this S56K variation will only work on linux and macOS until linux is implemented, duplicate of  
Duplicate of #1068

**Comment by EikelFlo** [comment] 2021-07-30 14:24
> this S56K variation will only work on linux and macOS until WinUSB is implemented, duplicate of
> Duplicate of #1068

> > Yeah, I have the same issue and my dump says Huion Tablet LuoYong70558 will just wait until its solved whenever the backlog is cleared
> 
> Open your own issue, this probably has nothing to do with your

**Closed by Mrcubix** 2021-07-30 14:23 UTC
Labels: support request

**Comment by Mrcubix** [comment] 2021-07-30 14:25
There has been working variations of the S56K, your isn't, that's it
