### ISSUE TITLE
Support Request: Cannot open the Plugin Manager

### ISSUE THREAD

**Issue by miyukowo** [OpenTabletDriver/OpenTabletDriver#982] opened 2021-04-12 16:54 UTC
# Support Request

I can't open the Plugin Manager to install plugins

## What I've already tried
I haven't done anything as I've no idea how to solve this

## Diagnostic Information

https://pastebin.com/Ebqp2CUs

**Comment by X9VoiD** [comment] 2021-04-12 16:56
Duplicate of #943

**Closed by X9VoiD** 2021-04-12 16:56 UTC
Labels: support request
