### ISSUE TITLE
Crash error on startup (MACOS)

### ISSUE THREAD

**Issue by SWAGEDGAR** [OpenTabletDriver/OpenTabletDriver#959] opened 2021-04-05 18:26 UTC
## Description

When clicked yes the error disappears then reappears. If clicked no the whole driver just closes.
![Screen Shot 2021-04-05 at 2 30 22 PM](https://user-images.githubusercontent.com/39568131/113610729-8257af00-961b-11eb-944e-a8fee374d66e.png)

## System Information:
![Screen Shot 2021-04-05 at 2 25 02 PM](https://user-images.githubusercontent.com/39568131/113610183-c4342580-961a-11eb-8122-f74e96a45a6d.png)

| Operating System |
MacOS
| Software Version |
0.5.2.3
| Tablet           |
Wacom CTL 472

**Comment by X9VoiD** [comment] 2021-04-05 19:18
Go to OTD -> Help -> Export Diagnostics, then upload it here in zip format.

**Comment by SWAGEDGAR** [comment] 2021-04-05 23:03
> Go to OTD -> Help -> Export Diagnostics, then upload it here in zip format.

Skip to 1:27 I somehow fixed it by clicking Export Diagnostics. (All the time before that is me trying to click the button)

**Comment by SWAGEDGAR** [comment] 2021-04-05 23:06
But if I close OTD it will say the error again for sure.

**Comment by InfinityGhost** [comment] 2021-04-06 01:30
Check if `~/Library/Application Support/OpenTabletDriver` exists, and if it does try deleting it.

**Comment by SWAGEDGAR** [comment] 2021-04-06 17:09
> Check if `~/Library/Application Support/OpenTabletDriver` exists, and if it does try deleting it.

So I was able to delete it but now it wont open just crash a full crash.

**Comment by nerelly** [comment] 2021-05-01 04:50
Same thing was happening to me. What I did to get it working was delete ~/Library/Application Support/OpenTabletDriver, open activity monitor and force quit opentabletdriver daemon.

**Comment by InfinityGhost** [comment] 2021-05-25 03:19
A workaround appears to exist at least for now, closing this as I've been unable to reproduce.

**Closed by InfinityGhost** 2021-05-25 03:19 UTC
Labels: bug, macos
