### ISSUE TITLE
mouse click issue

### ISSUE THREAD

**Issue by gamegeek7** [OpenTabletDriver/OpenTabletDriver#3331] opened 2024-05-31 17:05 UTC
### Steps to Reproduce

I recently bought a Vinsa 1060 Plus, which from what I can tell is just a rebranded 10moon 1060N. Positioning works fine, but when I press the pen down, nothing happens. I opened the tablet debugger and the driver does receive the pressure data but it doesn't seem to be translating it to a left click.
Sometime this would affect my mouse, and I cannot left click with it. Restarting Xorg enable me to left click with my mouse again but the problem with the tablet is still present.

### Expected Behavior

mouse is supposed to work

### Observed Behavior

never worked

### Tablet Device

10moons 1060N

### Diagnostic Information

none

### Acknowledgements

- [X] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.
- [X] I am on the latest version of OpenTabletDriver.

**Comment by jamesbt365** [comment] 2024-05-31 17:21
known breakage, see the TABLETS.md or website. Duplicate of #3176. There are multiple proposed PRs to "fix" this, see #2615 and #2853

**Closed by jamesbt365** 2024-05-31 17:21 UTC
Labels: bug, needs-triage
