### ISSUE TITLE
Add support for Wacom One 2023 (CTC6110WL)

### ISSUE THREAD

**Issue by KayTwoOne** [OpenTabletDriver/OpenTabletDriver#3113] opened 2023-12-19 16:41 UTC
### Manufacturer

Wacom

### Product Name

CTC-6110WL/CTC-HM

### Device Width

216

### Device Height

135

### Pressure Levels

8192

### Diagnostic Information

[diag.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/13718184/diag.txt)

### Acknowledgements

- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

**Comment by jamesbt365** [comment] 2023-12-19 16:44
Please check for duplicates. Duplicate of #3105, #3101 and #2993. Support was added in #2902 and will be available if you compile the current 0.6.x branch or wait for the next release.

**Closed by jamesbt365** 2023-12-19 16:44 UTC
Labels: duplicate, configuration
