### ISSUE TITLE
Sleep detection doesn't work anymore

### ISSUE THREAD

**Issue by thymue** [OpenTabletDriver/OpenTabletDriver#2044] opened 2022-02-04 14:18 UTC
## Description

I downloaded some build in between OTD 0.5.3.3 and 0.6.0.0 when I saw sleep detection was merged, now I updated to the latest version and when I put my PC into sleep and start it back the driver doesn't work again.
## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System         | Windows 10 21H2
| OpenTabletDriver Version | 0.6.0.3
| Tablet                   | Wacom CTL-472

**Comment by jamesbt365** [comment] 2022-02-04 14:22
Should be fixed in #2041

**Comment by vedattt** [comment] 2022-02-04 14:22
As James says, test an action build from #2041, see if it fixes the issue.
If it does, this is likely a duplicate of #1870.

**Closed** 2022-02-06 02:47 UTC
Labels: bug
