### ISSUE TITLE
GTK app crashes when it tries to detect the tablet

### ISSUE THREAD

**Issue by hadasfada** [OpenTabletDriver/OpenTabletDriver#1023] opened 2021-04-20 19:14 UTC
The daemon works but when I try to open the GTK app it tries to connect to the daemon gets stuck and then crashes.

Exception in Gtk# callback delegate
  Note: Applications can use GLib.ExceptionManager.UnhandledException to handle the exception.
System.NullReferenceException: Object reference not set to an instance of an object.
   at OpenTabletDriver.UX.MainForm.DetectAllTablets()
   at OpenTabletDriver.UX.MainForm.<ConstructMenu>b__11_7(Object sender, EventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at Eto.GtkSharp.Forms.GtkSynchronizationContext.<>c__DisplayClass0_0.<Post>b__0()
   at GLib.Idle.IdleProxy.Handler()
   at GLib.ExceptionManager.RaiseUnhandledException(Exception e, Boolean is_terminal)
   at GLib.Idle.IdleProxy.Handler()
   at Eto.GtkSharp.Forms.ApplicationHandler.Run()
   at Eto.Forms.Application.Run(Form mainForm)
   at OpenTabletDriver.UX.App.Run(String platform, String[] args)
   at OpenTabletDriver.UX.Gtk.Program.Main(String[] args)

System Information:
Operating System : openSUSE Tumbleweed
Version : 0.5.3.1
Tablet : Wacom CTL-472

**Comment by matiidenys** [comment] 2021-04-21 11:51
I may be wrong, but seems like it's the same issue we had with OTD on ArchLinux

**Comment by gonX** [comment] 2021-05-15 14:33
Duplicate of #896, should get fixed by #1104

**Comment by InfinityGhost** [comment] 2021-05-25 03:16
Resolved in #1104

**Closed by InfinityGhost** 2021-05-25 03:16 UTC
Labels: bug, gui, linux/gtk
