### ISSUE TITLE
OTD crashed when tablet width/height is 0 on Apple M1

### ISSUE THREAD

**Issue by rezikham** [OpenTabletDriver/OpenTabletDriver#3020] opened 2023-11-19 18:19 UTC
### Steps to Reproduce

1. Open OTD
2. Connect the tablet
3. Change width/height

### Expected Behavior

OTD set width/height at 0.

### Observed Behavior

OTD crashed the moment value is 0.

### Tablet Device

XPPen G640

### Diagnostic Information

[Untitled.json](https://github.com/OpenTabletDriver/OpenTabletDriver/files/13404274/Untitled.json)

### Acknowledgements

- [X] I have installed OpenTabletDriver by following its [official installation instructions](https://opentabletdriver.net/).
- [X] I have checked the [OpenTabletDriver Wiki](https://opentabletdriver.net/Wiki) and respective FAQ pages, and my issue was not covered or actually fixed.
- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.
- [X] I am on the latest version of OpenTabletDriver.

**Comment by jamesbt365** [comment] 2023-11-19 18:23
Duplicate of #2287

**Closed by jamesbt365** 2023-11-19 18:23 UTC
Labels: bug, needs-triage
