### ISSUE TITLE
(Ubuntu 21.04) The GTK app crashes before detecting the tablet.

### ISSUE THREAD

**Issue by noncomplete** [OpenTabletDriver/OpenTabletDriver#1139] opened 2021-06-02 12:56 UTC
## Description

The daemon is running. However, the GTK app crashes.

**Output from terminal:**
```
$ opentabletdriver

Exception in Gtk# callback delegate
  Note: Applications can use GLib.ExceptionManager.UnhandledException to handle the exception.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Gtk.Widget.DrawnSignalCallback(IntPtr inst, IntPtr arg0, IntPtr gch)
   at GLib.ExceptionManager.RaiseUnhandledException(Exception e, Boolean is_terminal)
   at Gtk.Widget.DrawnSignalCallback(IntPtr inst, IntPtr arg0, IntPtr gch)
   at Eto.GtkSharp.Forms.ApplicationHandler.Run()
   at Eto.Forms.Application.Run(Form mainForm)
   at OpenTabletDriver.UX.App.Run(String platform, String[] args)
   at OpenTabletDriver.UX.Gtk.Program.Main(String[] args)
```
```
$ systemctl --user status opentabletdriver

● opentabletdriver.service - OpenTabletDriver Daemon
     Loaded: loaded (/usr/lib/systemd/user/opentabletdriver.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2021-06-02 18:22:17 +06; 19min ago
   Main PID: 1557 (OpenTabletDrive)
     CGroup: /user.slice/user-1000.slice/user@1000.service/app.slice/opentabletdriver.service
             └─1557 /usr/share/OpenTabletDriver/OpenTabletDriver.Daemon -c /usr/share/OpenTabletDriver/Configurations

Jun 02 18:22:17 potato OpenTabletDriver.Daemon[1557]: [Settings:Info]        Express Key Bindings: [0, ], [1, ], [2, ], [3, ], [4, ], [5, ], [6, ], [7, ]
Jun 02 18:22:17 potato OpenTabletDriver.Daemon[1557]: [Settings:Info]        Driver is auto-enabled.
Jun 02 18:22:19 potato OpenTabletDriver.Daemon[1557]: [IPC:Debug]        Connected to a client.
Jun 02 18:22:21 potato OpenTabletDriver.Daemon[1557]: [IPC:Debug]        Disconnected from a client.
Jun 02 18:39:55 potato OpenTabletDriver.Daemon[1557]: [IPC:Debug]        Connected to a client.
Jun 02 18:39:57 potato OpenTabletDriver.Daemon[1557]: [IPC:Debug]        Disconnected from a client.
Jun 02 18:40:48 potato OpenTabletDriver.Daemon[1557]: [IPC:Debug]        Connected to a client.
Jun 02 18:40:49 potato OpenTabletDriver.Daemon[1557]: [IPC:Debug]        Disconnected from a client.
Jun 02 18:40:55 potato OpenTabletDriver.Daemon[1557]: [IPC:Debug]        Connected to a client.
Jun 02 18:40:56 potato OpenTabletDriver.Daemon[1557]: [IPC:Debug]        Disconnected from a client.
```

## System Information:

| Name             | Value |
| ---------------- | ----- |
| Operating System | Ubuntu 21.04 x86_64|
| Software Version | 0.5.3.1|
| Tablet           | XP-PEN Star G640|

**Comment by coinworld** [comment] 2021-06-02 13:31
This is duplicate of #896

You can try using one of recent [Actions builds](https://github.com/OpenTabletDriver/OpenTabletDriver/actions) or  [my build with update GUI library](https://github.com/OpenTabletDriver/OpenTabletDriver/files/6584847/otd0.5.3.1-updated-eto.tar.gz) (you can also compile it yourself)

**Closed** 2021-06-02 23:16 UTC
Labels: bug, duplicate
