### ISSUE TITLE
Add support for Parblo A640

### ISSUE THREAD

**Issue by BeanButCoffee** [OpenTabletDriver/OpenTabletDriver#1621] opened 2021-11-10 03:04 UTC
# Tablet Information

| Name            | Parblo A640 |
| --------------- | ----- |
| Manufacturer    | Parblo |
| Product Name    | A640 |
| Width           | 6 inches |
| Height          | 4 inches |
| Pressure Levels | 8192 |
| LPI             | 5080 |

## Diagnostic Information

[diag.txt](https://github.com/OpenTabletDriver/OpenTabletDriver/files/7509495/diag.txt)

**Comment by gonX** [comment] 2021-12-07 07:56
Duplicate of #586

**Closed by gonX** 2021-12-07 07:56 UTC
Labels: duplicate, configuration, support request
