### ISSUE TITLE
Support Request: Install has missing dependancies

### ISSUE THREAD

**Issue by posLop** [OpenTabletDriver/OpenTabletDriver#1463] opened 2021-09-24 18:00 UTC
I am trying to install on ubuntu 20 but whenever i try and install the opentanlet.deb i get a message saying that its msg

 opentabletdriver : Depends: libevdev-dev but it is not going to be installed
                    Depends: libappindicator3-dev but it is not going to be installed

ive tried installing those with apt but no luck

**Comment by InfinityGhost** [comment] 2021-09-24 18:11
Duplicate of #1454

**Closed by InfinityGhost** 2021-09-24 18:11 UTC
Labels: support request
