### ISSUE TITLE
Support Request: i cant use pressure sensitivity

### ISSUE THREAD

**Issue by claimax10** [OpenTabletDriver/OpenTabletDriver#1465] opened 2021-09-25 13:18 UTC
.

**Comment by Mrcubix** [comment] 2021-09-25 13:25
i should be clossing this issue for not being filled properly, but instead i'll close cause duplicate of so many other issues, do a bit of research next time

vmulti: https://github.com/X9VoiD/vmulti-bin/releases/latest
Windows Ink Plugin: Check Plugin > Plugin manager

set your tip to a windows ink tip binding (by clicking on the ... next to the normal binding box)
![image](https://user-images.githubusercontent.com/39861216/134773143-9c5bea1e-3d9d-42b4-87be-6ac0f5789f60.png)
![image](https://user-images.githubusercontent.com/39861216/134773152-176df549-afb3-481a-832c-2f0971f8eb3f.png)

**Closed by Mrcubix** 2021-09-25 13:25 UTC
Labels: support request
