### ISSUE TITLE
Add support for RTP-700

### ISSUE THREAD

**Issue by Janus-M** [OpenTabletDriver/OpenTabletDriver#3364] opened 2024-07-09 18:25 UTC
### Manufacturer

Huion

### Product Name

RTP-700

### Device Width

297,4mm

### Device Height

174.6mm

### Pressure Levels

8192

### Lines per Inch (LPI)

5080

### Additional Information

Full product dimension are 345,6x214,8x8,5mm and it has 6 touch buttons and touch bar placed 20mm to the left of working area.
I found old request for it, dowloaded it and tried to load that preset but it still didn't detected. Im noob so please if you can tell me step by step what I should do.

### Diagnostic Information

[Diag.json](https://github.com/user-attachments/files/16147718/Diag.json)

### Acknowledgements

- [X] I have searched the existing issues and this new issue is not a duplicate of any.
- [X] I have written a concise and meaningful title.

**Comment by jamesbt365** [comment] 2024-07-10 18:47
Please post this information in the original issue. It is much preferred to not duplicate posts.

Duplicate of #1445.

**Closed by jamesbt365** 2024-07-10 18:47 UTC
Labels: configuration, needs-triage
